name: Discord Updates
on: [pull_request, pull_request_review]

jobs:
  SendDiscordWebhook:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ${{ github.actor }} has raised a pull request! ðŸš€
            Please review: ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.html_url }}